/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author martaniadewi
 */
public class ListBarang extends javax.swing.JFrame {

    /**
     * Creates new form ListBarang
     */
    public ListBarang() {
        initComponents();
    }
    public void listener(ActionListener al) {
        ButtonPinjam.addActionListener(al);
        ButtonBack.addActionListener(al);
        ButtonCari.addActionListener(al);
        ButtonRefresh.addActionListener(al);
        ButtonBalikin.addActionListener(al);
        ButtonTampilPinjaman.addActionListener(al);
    }
    public JButton getButtonBack() {
        return ButtonBack;
    }

    public JButton getButtonBalikin() {
        return ButtonBalikin;
    }

    public void setButtonBalikin(JButton ButtonBalikin) {
        this.ButtonBalikin = ButtonBalikin;
    }

    public JButton getButtonTampilPinjaman() {
        return ButtonTampilPinjaman;
    }

    public void setButtonTampilPinjaman(JButton ButtonTampilPinjaman) {
        this.ButtonTampilPinjaman = ButtonTampilPinjaman;
    }
    

    public void setButtonBack(JButton ButtonBack) {
        this.ButtonBack = ButtonBack;
    }

    public JButton getButtonPinjam() {
        return ButtonPinjam;
    }

    public void setButtonPinjam(JButton ButtonPinjam) {
        this.ButtonPinjam = ButtonPinjam;
    }

    public JButton getButtonCari() {
        return ButtonCari;
    }

    public void setButtonCari(JButton ButtonCari) {
        this.ButtonCari = ButtonCari;
    }

    public JToggleButton getButtonRefresh() {
        return ButtonRefresh;
    }

    public void setButtonRefresh(JToggleButton ButtonRefresh) {
        this.ButtonRefresh = ButtonRefresh;
    }

    public JTextArea getTextAreaTampilBarang() {
        return TextAreaTampilBarang;
    }

    public void setTextAreaTampilBarang(JTextArea TextAreaTampilBarang) {
        this.TextAreaTampilBarang = TextAreaTampilBarang;
    }

    public JTextField getTextFieldCarId() {
        return TextFieldCarId;
    }

    public void setTextFieldCarId(JTextField TextFieldCarId) {
        this.TextFieldCarId = TextFieldCarId;
    }

    public JTextField getTextFieldIdAnggota() {
        return TextFieldIdAnggota;
    }

    public void setTextFieldIdAnggota(JTextField TextFieldIdAnggota) {
        this.TextFieldIdAnggota = TextFieldIdAnggota;
    }

    public JTextField getTextFieldIdBarang() {
        return TextFieldIdBarang;
    }

    public void setTextFieldIdBarang(JTextField TextFieldIdBarang) {
        this.TextFieldIdBarang = TextFieldIdBarang;
    }

    public JTextField getTextFieldIdPinjam() {
        return TextFieldIdPinjam;
    }

    public void setTextFieldIdPinjam(JTextField TextFieldIdPinjam) {
        this.TextFieldIdPinjam = TextFieldIdPinjam;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaTampilBarang = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        TextFieldCarId = new javax.swing.JTextField();
        ButtonCari = new javax.swing.JButton();
        ButtonRefresh = new javax.swing.JToggleButton();
        ButtonTampilPinjaman = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextFieldIdAnggota = new javax.swing.JTextField();
        TextFieldIdBarang = new javax.swing.JTextField();
        TextFieldIdPinjam = new javax.swing.JTextField();
        ButtonPinjam = new javax.swing.JButton();
        ButtonBack = new javax.swing.JButton();
        ButtonBalikin = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 255));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));

        TextAreaTampilBarang.setColumns(20);
        TextAreaTampilBarang.setForeground(new java.awt.Color(0, 0, 255));
        TextAreaTampilBarang.setRows(5);
        jScrollPane1.setViewportView(TextAreaTampilBarang);

        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Search by id: ");

        TextFieldCarId.setForeground(new java.awt.Color(0, 0, 255));

        ButtonCari.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        ButtonCari.setForeground(new java.awt.Color(0, 0, 255));
        ButtonCari.setText("CARI");
        ButtonCari.setToolTipText("");
        ButtonCari.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        ButtonRefresh.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        ButtonRefresh.setForeground(new java.awt.Color(0, 0, 255));
        ButtonRefresh.setText("REFRESH");
        ButtonRefresh.setToolTipText("");
        ButtonRefresh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        ButtonTampilPinjaman.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        ButtonTampilPinjaman.setForeground(new java.awt.Color(0, 0, 255));
        ButtonTampilPinjaman.setText("TAMPIL PINJAMAN");
        ButtonTampilPinjaman.setToolTipText("");
        ButtonTampilPinjaman.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextFieldCarId, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonCari, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonTampilPinjaman)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonRefresh)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextFieldCarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonRefresh)
                    .addComponent(ButtonTampilPinjaman))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LIST BARANG", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("ID ANGGOTA : ");

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("ID BARANG :");

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("ID PEMINJAMAN :");

        TextFieldIdAnggota.setForeground(new java.awt.Color(0, 0, 255));

        TextFieldIdBarang.setForeground(new java.awt.Color(0, 0, 255));
        TextFieldIdBarang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TextFieldIdPinjam.setForeground(new java.awt.Color(0, 0, 255));
        TextFieldIdPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIdPinjamActionPerformed(evt);
            }
        });

        ButtonPinjam.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        ButtonPinjam.setForeground(new java.awt.Color(0, 0, 255));
        ButtonPinjam.setText("PINJAM");
        ButtonPinjam.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        ButtonPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPinjamActionPerformed(evt);
            }
        });

        ButtonBack.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        ButtonBack.setForeground(new java.awt.Color(0, 0, 255));
        ButtonBack.setText("<- BACK");
        ButtonBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        ButtonBalikin.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        ButtonBalikin.setForeground(new java.awt.Color(0, 0, 255));
        ButtonBalikin.setText("KEMBALIKAN");
        ButtonBalikin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonBack)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ButtonBalikin, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldIdBarang, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextFieldIdAnggota, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextFieldIdPinjam, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(TextFieldIdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldIdPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonPinjam)
                    .addComponent(ButtonBack)
                    .addComponent(ButtonBalikin))
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("FORM PEMINJAMAN", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldIdPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIdPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldIdPinjamActionPerformed

    private void ButtonPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPinjamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonBalikin;
    private javax.swing.JButton ButtonCari;
    private javax.swing.JButton ButtonPinjam;
    private javax.swing.JToggleButton ButtonRefresh;
    private javax.swing.JButton ButtonTampilPinjaman;
    private javax.swing.JTextArea TextAreaTampilBarang;
    private javax.swing.JTextField TextFieldCarId;
    private javax.swing.JTextField TextFieldIdAnggota;
    private javax.swing.JTextField TextFieldIdBarang;
    private javax.swing.JTextField TextFieldIdPinjam;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
